---
- name: Apache server installed
  hosts: web*
  become: yes
  tasks:
  - name: Display hostname
    debug:
      msg: "Host Name - {{ ansible_hostname }}"

  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started

  - name: Ansible create file with content example
    copy:
      dest: "/var/www/html/index.html"
      content: |
        <body>
        <h1>Apache is running fine</h1>
        </body>
  
  - name: Open port 80 for http access
    firewalld:
      service: http
      permanent: true
      state: enabled
      
  - name: Restart the firewalld service to load in the firewall changes
    service: 
      name: firewalld 
      state: restarted
  
  - name: Smoke test
    action: uri url=http://{{ ansible_hostname }} return_content=yes
    register: webpage

  - fail:
      msg: 'service is not happy'
    when: "'Apache is running fine' not in webpage.content"
