- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - set_fact:
        mount: "{{ ansible_mounts | first }}"                                                                                                                       
    - set_fact: disk_usage="{{ mount.size_total - mount.size_available }}"
    - set_fact: disk_usage_ratio="{{ disk_usage|float / mount.size_total }}"
    - set_fact: disk_usage_s="{{ (disk_usage|float / 1000000000) | round(1, 'common') }}GB"
    - set_fact: disk_total_s="{{ (mount.size_total / 1000000000) | round(1, 'common') }}GB"
    - set_fact: disk_usage_ratio_s="{{ 100 * (disk_usage_ratio|float) | round(1, 'common') }}%"
                                                                                                                        
    - debug:
        msg: "disk usage {{ disk_usage_s }} of total {{ disk_total_s }} ({{ disk_usage_ratio_s }})"
